### ISSUE TITLE
Decode the received message

### ISSUE THREAD

**Issue by Tigersx** [etherkit/JTEncode#12]
Hello,

First of, I would like to thank you for this great library, it works amazingly well.
My question is, is it possible to decode the received signal using an Arduino. For the project I'm working on I need to be able to send and receive the signal with an Arduino using the JT65 protocol.

**Comment by NT7S** [comment]
Thank you, glad you find the library useful!

Decoding these signals is a completely different problem domain, requiring the use of an ADC for sampling the baseband signal and DSP routines in order to demodulate. I think it is probably within the capability of the more powerful ARM-based Arduino platforms, but not likely doable on something like an Uno. Because this is so far out of the scope of encoding JT messages, it's not something I can include in this library. Perhaps, once I acquire more DSP skills, I can try to write a separate decode library, but I can't make any promises there.
